# Generated by Django 4.2.13 on 2024-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurehistory",
            name="currency",
            field=models.CharField(default="€", max_length=10),
        ),
    ]
